# Generated by Django 5.0.1 on 2024-04-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_category_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
